# Generated by Django 4.2.2 on 2023-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_AFPA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('logo', models.CharField(max_length=255)),
                ('nom_ligue', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=80)),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ligue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rencontre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_match', models.DateField()),
                ('num_journee', models.IntegerField(default=0)),
                ('equipe_dom', models.CharField(max_length=60)),
                ('equipe_vis', models.CharField(max_length=60)),
                ('buts_dom', models.IntegerField(default=0)),
                ('buts_vis', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
